// <auto-generated />
using System;
using JwtSecureApiService.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JwtSecureApiService.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JwtSecureApiService.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Colombo, Sri Lanka",
                            DepartmentName = "Development",
                            Name = "Manoj"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Colombo, Sri Lanka",
                            DepartmentName = "Marketing",
                            Name = "Manee"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Colombo, Sri Lanka",
                            DepartmentName = "Development",
                            Name = "Malin"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Colombo, Sri Lanka",
                            DepartmentName = "HR",
                            Name = "Harshi"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Colombo, Sri Lanka",
                            DepartmentName = "Finance",
                            Name = "Mahinda"
                        });
                });

            modelBuilder.Entity("JwtSecureApiService.Models.LoginModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoginModels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "alex@123",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Alex"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
